sudo: false
language: node_js
node_js:
  - 9.4.0
script: 
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: www
  on:
    branch: master